import type { Association } from "./types";

export const associations: Association[] = [
  {
    id: "acca",
    name: "ACCA - Association Communale de Chasse Agréée d'Allaire",
    description: "Chasse au gibier sédentaire et migrateurs, régulation des ESOD (sangliers, renards, etc.)",
    icon: "Crosshair",
    categories: ["Loisirs", "Nature"],
    schedule: "Ouverture septembre à février selon arrêté préfectoral",
    contacts: [
      { name: "Christian Deleter", role: "Président", phone: "06 33 68 09 22", email: "christian.deleter@orange.fr" },
      { name: "René Pichon", role: "Vice-président", phone: "06 74 46 93 57" },
      { name: "Mickaël Boulo", role: "Trésorier", phone: "06 81 20 54 78" },
    ],
  },
  {
    id: "action-sociale-mobilite-solidaire",
    name: "Action Sociale - Mobilité Solidaire",
    description: "Transport bénévole pour personnes en difficulté de mobilité",
    icon: "Car",
    categories: ["Social", "Seniors"],
    schedule: "Du lundi au vendredi (sauf exception)",
    contacts: [{ name: "Contact", phone: "06 83 16 89 48" }],
    fee: "0,40€/km à partir du domicile de l'accompagnateur",
  },
  {
    id: "admr-allaire",
    name: "ADMR d'Allaire et sa région",
    description: "Services d'aide à domicile (ménage, repas, aide aux personnes âgées/handicapées)",
    icon: "Home",
    categories: ["Social", "Seniors", "Santé"],
    schedule: "Intervention 7j/7, secrétariat du lundi au vendredi",
    contacts: [
      { name: "Guy Viaud", role: "Président", phone: "02 99 91 09 05" },
      { name: "Secrétariat", phone: "02 99 71 85 77", email: "allaire@admr56.com" },
    ],
    location: "14 rue de la Libération, 56350 ALLAIRE",
  },
  {
    id: "alsh-o-merveilles",
    name: "ALSH O'Merveilles",
    description: "Accueil de loisirs municipal pour enfants 3-11 ans",
    icon: "ToyBrick",
    categories: ["Enfants"],
    schedule: "Centre : 9h-17h\nGarderie : 7h30-9h et 17h-18h30",
    contacts: [
      { name: "Virginie Mangouëro ou Noémie Mahé", phone: "02 99 71 86 08 / 06 59 71 68 26", email: "alsh@allaire.bzh" },
    ],
    location: "Maison du Temps Libre, 6 rue Saint Hilaire",
  },
  {
    id: "alternatives-rolistes",
    name: "Alternatives Rôlistes",
    description: "Découverte et pratique du jeu de rôle dans un cadre inclusif",
    icon: "Dices",
    categories: ["Loisirs", "Jeunesse"],
    contacts: [{ name: "Contact", phone: "06 19 37 02 42", email: "alternatives.rolistes@gmail.com" }],
    location: "Ludothèque",
  },
  {
    id: "amap-bois",
    name: "AMAP Bois",
    description: "Gestion durable des forêts locales, vente de bois via contrats AMAP",
    icon: "Trees",
    categories: ["Environnement", "Local"],
    contacts: [{ name: "Contact", phone: "06 95 34 49 88", email: "amap.allaire.bois@mailo.bzh" }],
  },
  {
    id: "a-ma-portee-amap",
    name: "À ma Portée - AMAP paniers diversifiés",
    description: "Légumes, produits laitiers, pain, volailles, œufs bio et locaux",
    icon: "Carrot",
    categories: ["Local", "Environnement"],
    schedule: "Mercredi 18h30-19h30 (jeudi pour volaille mensuellement)",
    contacts: [
      { name: "Catherine Guillemot", phone: "02 99 71 83 65 / 06 42 75 24 15" },
      { name: "Michaël Lefèvre", phone: "06 08 52 00 85", email: "amaportee@gmail.com" },
    ],
    location: "Bar associatif Au Bon Muscadet, Place de l'Église",
    fee: "Adhésion : 15€/an",
  },
  {
    id: "a-corps-danses",
    name: "À Corps Dansés",
    description: "Biodanza et Sophrodanse pour expression et bien-être",
    icon: "PersonStanding",
    categories: ["Bien-être", "Danse", "Culture"],
    schedule: "Biodanza : Mardi 19h-21h30\nSophrodanse : Jeudi tous les 15 jours 19h-20h30",
    contacts: [
      { name: "Manuela Bigot", phone: "06 83 78 70 46", email: "manubigot.biodanza@gmail.com" },
      { name: "Audrey Duez", role: "Secrétaire" },
    ],
    location: "Ferme de Coueslé",
    fee: "Biodanza 320€/an, Sophrodanse 160€/an",
  },
  {
    id: "les-amis-de-la-moto",
    name: "Les Amis de la moto d'Allaire",
    description: "Balades moto, visites, participation manifestations caritatives",
    icon: "Bike",
    categories: ["Loisirs", "Sport"],
    contacts: [{ name: "Philippe Michelo", phone: "06 60 74 26 52", email: "lesamisdelamotodallaire@gmail.com" }],
    fee: "Carte membre 25€",
  },
  {
    id: "arnb-randonneurs-naturistes",
    name: "ARNB - Association des Randonneurs Naturistes de Bretagne",
    description: "Randonnée naturiste, bowling, sorties en mer",
    icon: "Footprints",
    categories: ["Loisirs", "Nature"],
    schedule: "En journée (exceptés mercredi, week-end, jours fériés)",
    contacts: [
      { name: "Alain Cochet", role: "Président" },
      { name: "Patrice Chaudeur Mauriamé", role: "Trésorier" },
      { name: "Contact", email: "contact@arnb.fr" },
    ],
    website: "arnb.fr",
  },
  {
    id: "conjoints-survivants",
    name: "Association de conjoints survivants et parents d'orphelins du Morbihan",
    description: "Accueil et aide aux personnes frappées par le veuvage",
    icon: "HeartHandshake",
    categories: ["Social"],
    schedule: "Permanences Vannes mardi & jeudi 14h-17h",
    contacts: [{ name: "Contact", phone: "02 97 47 42 80", email: "asso.veuves56@orange.fr" }],
    location: "Maison de la Famille, 47 rue Ferdinand le Dressay, VANNES",
  },
  {
    id: "au-bon-muscadet",
    name: "Au Bon Muscadet",
    description: "Lieu de rencontre, concerts, théâtre, sessions, valorisation produits locaux",
    icon: "Beer",
    categories: ["Culture", "Loisirs", "Local"],
    schedule: "Vendredi à partir de 16h30 (été) ou 18h (hiver)",
    contacts: [{ name: "Contact", email: "aubonmus@gmail.com" }],
    website: "aubonmuscadet.fr",
    location: "Place de l'Église",
    fee: "Adhésion prix libre",
  },
  {
    id: "bouille-de-mome",
    name: "Bouille de Môme",
    description: "Organisation concerts et événements culturels, Festival TouT VenanT",
    icon: "Music2",
    categories: ["Culture", "Musique", "Événementiel"],
    contacts: [{ name: "Jules Berthe", phone: "06 38 81 10 51", email: "bouille2mome@yahoo.fr" }],
  },
  {
    id: "cacha",
    name: "CACHA - Comité d'Action Catholique et Humanitaire d'Allaire",
    description: "Collecte vieux papiers, journaux, cartons pour associations caritatives",
    icon: "Recycle",
    categories: ["Social", "Environnement"],
    contacts: [{ name: "Jean-Claude Dayon", phone: "02 99 71 94 10" }],
    location: "Lieux collecte : Presbytère & remorque Vaujouan (journaux), Vaujouan (cartons)",
  },
  {
    id: "centre-psychophonie-heliogramme",
    name: "Centre Psychophonie Héliogramme",
    description: "Harmonie par le chant, pose de voix, formation humaine",
    icon: "Music",
    categories: ["Bien-être", "Musique", "Culture"],
    schedule: "Jeudi 19h-21h à partir du 18 septembre 2025 (tous les 15 jours)",
    contacts: [
      { name: "Jeanne Le Gall", role: "Vice-présidente" },
      { name: "Solange Delbassée", phone: "02 99 71 95 88 / 06 64 33 28 70", email: "centreheliogramme@orange.fr" },
    ],
    location: "171, les Charbonnais, Route de Deil",
  },
  {
    id: "clac",
    name: "CLAC",
    description: "Accès culture et loisirs, activités variées enfants/adultes",
    icon: "Palette",
    categories: ["Culture", "Loisirs", "Sport", "Enfants", "Jeunesse"],
    schedule: "Permanences Sept-oct : mardi, mercredi, jeudi 14h-17h30\nPermanences Nov-juin : mercredi 14h-17h30",
    contacts: [{ name: "Contact", phone: "02 99 71 87 96", email: "contact@clacallaire.org" }],
    website: "www.clacallaire.org",
    location: "Centre associatif, 19 rue de Redon",
    activities: [
      {
        category: "Enfants",
        items: [
          { name: "Baby Gym (2-4 ans)", details: "Lundi 17h-17h45", price: "75€/an" },
          { name: "Gymnastique enfants (4-12 ans)", details: "Mercredi/Samedi selon âges", price: "75-80€/an" },
          { name: "Art thérapie enfants-parents (CP+)", details: "Samedi 11h30-12h30", price: "95€" },
          { name: "Sophrologie Enfant (6-10 ans)", details: "Jeudi 17h15-18h", price: "110€/an" },
          { name: "Danse Hip-hop (7+)", details: "Lundi 18h-19h/19h-20h", price: "135€/an" },
          { name: "Danse expression libre (5-7 ans)", details: "Mardi 17h-17h45", price: "135€/an" },
          { name: "Danse improvisée (8-12 ans)", details: "Mardi 18h-19h", price: "150€/an" },
          { name: "Improvisation théâtrale (8+)", details: "Mercredi 13h30-14h30/15h-16h30", price: "180-200€/an" },
          { name: "Multisports (5-10 ans)", details: "Mercredi 13h30-14h30/15h-16h", price: "80€/an" },
          { name: "Chorale Ramdam (7+ et parents)", details: "Samedi 10h-11h", price: "120-200€/an" },
        ],
      },
      {
        category: "Enfants et Adultes",
        items: [
          { name: "Bande dessinée (10+)", details: "Mercredi 15h-17h", price: "187€/an" },
          { name: "Dessin et peinture (10+)", details: "Lundi 17h-18h30/18h-20h", price: "150-200€/an" },
          { name: "Couture (12+)", details: "Samedi 9h30-12h30/14h-17h", price: "200€/an" },
          { name: "Badminton (15+)", details: "Jeudi dès 17h15", price: "35€/an" },
        ],
      },
      {
        category: "Adultes",
        items: [
          { name: "Atelier d'écriture (15+)", details: "Jeudi 17h-19h", price: "60€/an" },
          { name: "Sophrologie (15+)", details: "Jeudi 18h30-19h30", price: "130€/an" },
          { name: "Art floral", details: "Mardi 14h-16h/20h-22h", price: "80€/an" },
          { name: "Art thérapie", details: "Samedi 9h30-11h", price: "90€" },
          { name: "Découverte des vins", details: "Mardi 20h-22h", price: "100€/an" },
          { name: "Gymnastique douce", details: "Lundi 18h-19h/19h-20h", price: "80€/an" },
          { name: "Vannerie", details: "Mardi selon calendrier", price: "150€/an" },
          { name: "Pilates adapté", details: "Vendredi 18h-19h", price: "160€/an" },
          { name: "Yoga", details: "Lundi/Mardi/Mercredi/Jeudi selon créneaux", price: "250€/an" },
        ],
      },
    ],
    events: [
        { name: "Spect'allaire - Cinétoiles", date: "19 septembre 2025" },
        { name: "Spect'allaire - Festival Itinérances", date: "24-25 janvier 2026" },
        { name: "Spect'allaire - Mars à CLAC", date: "21 mars 2026" },
        { name: "Spect'allaire - Fête de la Bascule", date: "30-31 mai 2026" },
    ]
  },
  {
    id: "clara",
    name: "CLARA - Club de loisirs et d'animation des retraités d'Allaire",
    description: "Rencontres amicales, jeux, voyages, gymnastique pour retraités",
    icon: "Users",
    categories: ["Seniors", "Loisirs", "Sport"],
    schedule: "Jeux : 2ème et 4ème jeudis\nDanse, pétanque, cartes : mardis après-midi\nGymnastique : mardi 10h-11h15\nMarche : 2ème lundi du mois + lundis/jeudis 9h30-10h30",
    contacts: [
      { name: "Jean-Luc Duchesne", role: "Président", phone: "02 99 71 82 89 / 06 33 48 13 69" },
      { name: "Christine Berthe", role: "Secrétaire", phone: "06 61 59 32 07" },
    ],
    fee: "Adhésion : 17€",
  },
  {
    id: "club-socios",
    name: "Club Socios",
    description: "Organisation Trail des Jambes Allaire (courses enfants/adultes)",
    icon: "Trophy",
    categories: ["Sport", "Événementiel"],
    contacts: [{ name: "Yann Le Clouërec", phone: "06 52 32 69 75", email: "organisation.trail.allaire@gmail.com" }],
    website: "traildesjambesallaire.fr",
  },
  {
    id: "club-saint-gaudence-basketball",
    name: "Club Saint Gaudence - Basketball",
    description: "70 adhérents, 6 catégories U9 à seniors",
    icon: "Basketball",
    categories: ["Sport"],
    schedule: "Jeunes mardi/mercredi/vendredi soir, Seniors vendredi soir",
    contacts: [{ name: "Léa Sérot", phone: "07 82 79 17 31", email: "stgaudence.basket@gmail.com" }],
    location: "Salle Omnisports",
    fee: "80€ jeunes et seniors",
  },
  {
    id: "club-saint-gaudence-petanque",
    name: "Club Saint Gaudence - Pétanque",
    description: "Entraînements, concours, championnats, participation Téléthon",
    icon: "Circle",
    categories: ["Sport", "Seniors"],
    schedule: "Entraînements mardi/vendredi 14h-20h, concours samedi/dimanche",
    contacts: [
      { name: "Patrick Bavent", role: "Président", phone: "06 15 09 28 64", email: "pavent@free.fr" },
      { name: "Hugues Le Chesne", role: "Trésorier" },
      { name: "Jean-Louis Revert", role: "Secrétaire" },
    ],
    location: "Stade municipal",
    fee: "Licence 37€, Carte membre 22€",
  },
  {
    id: "club-saint-gaudence-football",
    name: "Club Saint Gaudence - Football",
    description: "École de foot, jeunes, seniors, sport loisirs",
    icon: "Futbol",
    categories: ["Sport"],
    schedule: "Jeunes: entraînements mardi/mercredi/jeudi, matchs samedi\nSeniors: entraînements mercredi/vendredi, matchs dimanche\nSport loisirs: matchs vendredi soir",
    contacts: [
      { name: "Damien Méhat", role: "Président", phone: "06 64 92 58 85" },
      { name: "Gilles Launay", role: "VP seniors", phone: "07 89 87 07 64" },
      { name: "Arnaud Tourneux", role: "VP école foot", phone: "06 74 44 11 36" },
      { name: "Cyrille Goislard", role: "VP GJPA", phone: "06 09 59 38 63" },
      { name: "Rémi Paris", role: "Secrétaire", phone: "06 81 10 09 69" },
    ],
    location: "Stade municipal",
    fee: "U6-U7: 75€, U8-U13: 85€, U14-U18: 90€, Seniors: 110€",
  },
  {
    id: "club-saint-gaudence-cyclo-vtt-marche",
    name: "Club Saint Gaudence - Club Cyclo VTT Marche",
    description: "Cyclotourisme, VTT, marche sans compétition",
    icon: "Bike",
    categories: ["Sport", "Nature"],
    schedule: "Marche-VTT : Dimanche 8h30\nCyclo : Dimanche matin (8h15/8h30/9h selon période)",
    contacts: [{ name: "Remy Potier", phone: "06 73 92 34 77", email: "remy.potier1@orange.fr" }],
    location: "Terrain des sports",
    fee: "Licence FFVélo 54,50€ adultes/38€ -25ans, FFRandonnée 28,70€",
  },
  {
    id: "club-saint-gaudence-judo",
    name: "Club Saint Gaudence - Judo Club d'Allaire",
    description: "Judo dès 4 ans, découverte self-défense/jujitsu/taiso",
    icon: "Medal",
    categories: ["Sport", "Arts Martiaux", "Enfants"],
    schedule: "Mardi/Jeudi selon catégories d'âge (17h30-20h30)",
    contacts: [
      { name: "Sophie Jan", role: "Présidente", phone: "06 79 84 19 95", email: "judocluballaire@gmail.com" },
      { name: "Christelle Moudurier", role: "Secrétaire" },
      { name: "Pierre & Alexandre Hurtel", role: "Trésoriers" },
    ],
    location: "Dojo Salle Omnisports",
    fee: "Baby: 142€, 2018-2011: 172€, 2010+: 192€ (+ 20€ hors Allaire)",
  },
  {
    id: "club-saint-gaudence-tennis",
    name: "Club Saint Gaudence - Tennis Club d'Allaire",
    description: "Tennis loisir/compétition, école de tennis dès 4 ans",
    icon: "TennisBall",
    categories: ["Sport", "Enfants"],
    schedule: "École tennis: Lundi 17h15-20h, Mercredi 16h15-19h45, Jeudi 17h30-18h45\nAdultes: Lundi 20h-21h45, Mardi 20h-21h45, Samedi 9h45-11h30",
    contacts: [
      { name: "Jean-Louis Torlay", role: "Président", phone: "06 85 85 28 84" },
      { name: "Wendy Potier", role: "Secrétaire", email: "tcallaire@gmail.com" },
      { name: "Mickaël Levallois", role: "Trésorier", phone: "07 55 59 42 33" },
    ],
    location: "Salle des sports",
    fee: "110-180€ selon niveau",
  },
  {
    id: "comite-animations-maison-retraite",
    name: "Comité d'animations maison de retraite d'Allaire",
    description: "Aide financière résidents pour événements et animations",
    icon: "Gift",
    categories: ["Seniors", "Social"],
    contacts: [
      { name: "Chantal Mattera", role: "Présidente", phone: "06 67 59 49 46" },
      { name: "Catherine Mignet", role: "VP", phone: "02 99 71 87 53" },
    ],
    location: "EHPAD, 5 rue des Bruyères",
  },
  {
    id: "la-compagnie-des-voix",
    name: "La Compagnie des Voix",
    description: "Ateliers expression orale/corporelle, spectacles voix",
    icon: "Voicemail",
    categories: ["Culture", "Théâtre", "Musique"],
    activities: [
      { category: "Ateliers", items: [{ name: "Chant Trad DEDANS-DEHORS", details: "1 mercredi/mois 18h-19h30", price: "80€+5€" }] }
    ],
    events: [
        { name: "Le P'tit Cabaret Sonné", date: "Week-end 15-16 novembre 2025" }
    ],
    contacts: [
      { name: "Accompagnement", email: "laciedesvoix@gmail.com" },
      { name: "Direction artistique", email: "annegaelle.bzh@gmail.com", phone: "06 60 65 02 22" },
    ],
    location: "260, Le Val de Vilaine / Bocquéreaux / Ferme de Coueslé",
  },
  {
    id: "conseil-municipal-enfants",
    name: "Conseil Municipal d'Enfants",
    description: "Dialogue adultes-enfants, projets communaux pour 9-11 ans",
    icon: "MessageSquare",
    categories: ["Enfants", "Citoyenneté"],
    contacts: [
      { name: "Séverine Mahé", role: "Adjointe enfance jeunesse" },
      { name: "Virginie Mangouëro", phone: "06 59 71 68 26", email: "vmangouerohercelin@allaire.bzh" },
    ],
  },
  {
    id: "donneurs-de-sang",
    name: "Donneurs de sang de Saint-Jacut-les-Pins et sa région",
    description: "Organisation collectes Allaire, Saint-Jacut, Malansac, Peillac",
    icon: "Droplet",
    categories: ["Santé", "Social"],
    contacts: [
      { name: "Jean-François Berthe", role: "VP", phone: "02 56 24 99 11" },
      { name: "Jean-Paul Burban", role: "VP", phone: "02 99 71 90 56" },
      { name: "Marie-Noëlle Ollivier", role: "Secrétaire", phone: "02 99 91 35 74" },
      { name: "Hubert Nué", role: "Trésorier", phone: "02 99 91 84 45" },
    ],
  },
  {
    id: "dynamikair",
    name: "Dynamik'air",
    description: "Cross-training, kick boxing, aérokick",
    icon: "Flame",
    categories: ["Sport", "Arts Martiaux"],
    contacts: [{ name: "Contact", phone: "07 83 29 66 78", email: "dynamikair35@gmail.com" }],
  },
  {
    id: "amicale-ecole-renaudeau",
    name: "Amicale école Renaudeau",
    description: "Récolte fonds projets pédagogiques, événements familiaux",
    icon: "School",
    categories: ["Enfants", "Éducation", "Événementiel"],
    events: [
        { name: "Fun Allaire", date: "22-23 nov" },
        { name: "Noël", date: "" },
        { name: "Chasse aux œufs", date: "" },
        { name: "Vide grenier", date: "" },
        { name: "Fête de l'école", date: "" },
    ],
    contacts: [
      { name: "Maximilien Sourdril", role: "Président", phone: "07 82 34 69 00" },
      { name: "Marie Duveau", role: "Trésorière" },
      { name: "Intissar Legal", role: "Vice-trésorière" },
      { name: "Antoine Martin", role: "Secrétaire" },
    ],
  },
  {
    id: "apel-college-saint-hilaire",
    name: "APEL - Collège Saint-Hilaire",
    description: "Parents bénévoles vie/animation collège, représentation instances",
    icon: "GraduationCap",
    categories: ["Jeunesse", "Éducation"],
    contacts: [
      { name: "Maryline Naël", role: "Présidente", phone: "06 61 53 76 02" },
      { name: "Laurence Magré", role: "Secrétaire" },
      { name: "Michaël Morel", role: "Trésorier" },
    ],
  },
  {
    id: "apel-ecole-sainte-anne",
    name: "APEL - École Sainte-Anne",
    description: "Parents bénévoles financement sorties/activités, animations",
    icon: "School",
    categories: ["Enfants", "Éducation", "Événementiel"],
    events: [
        { name: "Belote", date: "octobre" },
        { name: "Marché Noël", date: "décembre" },
        { name: "Kermesse", date: "juin" },
    ],
    contacts: [
      { name: "Nathalie Bourdiec", role: "Présidente" },
      { name: "Carole Noury-Ducasse", role: "Secrétaire", phone: "06 42 89 30 10", email: "apel.ecole.allaire56@gmail.com" },
      { name: "Pascal Andrieux", role: "Chef établissement", phone: "02 99 71 91 19" },
    ],
    location: "26 rue de Deil",
  },
  {
    id: "ecole-de-musique-traditionnelle",
    name: "École de Musique Traditionnelle",
    description: "Enseignement musique traditionnelle, transmission orale",
    icon: "Music3",
    categories: ["Musique", "Culture", "Éducation"],
    schedule: "Mercredi : Éveil 16h30-17h15, Découverte 17h15-18h, cours instruments 14h30-21h\nAteliers : Pratique collective 18h-18h45, groupe ados après-midi, adultes 20h30",
    contacts: [{ name: "Contact", phone: "02 99 71 36 50", email: "ecole@gcbpv.org" }],
    website: "gcbpv.org",
    fee: "Éveil 90€, Découverte 140€, Instruments 310/350€, Ateliers 125€",
  },
  {
    id: "les-ecuries-du-petit-manoir",
    name: "Les Écuries du Petit Manoir",
    description: "Centre équestre, poneys-club, équi-handi, randonnées",
    icon: "Horse",
    categories: ["Sport", "Animaux", "Enfants"],
    schedule: "Mardi-vendredi 14h-18h pour infos",
    contacts: [{ name: "Sylvie Sigrist", phone: "06 20 50 10 26" }],
    location: "71 Séjourné",
  },
  {
    id: "equilibre-et-bien-etre",
    name: "Équilibre et Bien-être",
    description: "Cours équilibre et mouvements doux pour seniors",
    icon: "HeartPulse",
    categories: ["Seniors", "Bien-être", "Santé"],
    schedule: "Mercredi 14h-15h30 (17 sept-24 juin)",
    contacts: [
      { name: "Myriam Charles", role: "Présidente", phone: "02 99 71 90 97", email: "myriam-charles@orange.fr" },
      { name: "Yvette Ménager", role: "Secrétaire", phone: "02 99 71 86 36" },
    ],
    fee: "55€",
  },
  {
    id: "espace-jeunes",
    name: "Espace Jeunes",
    description: "Lieu rencontre 10+ ans, activités vacances",
    icon: "Gamepad2",
    categories: ["Jeunesse", "Loisirs"],
    schedule: "Hors vacances : Mercredi/samedi 14h-18h30\nVacances : Lundi-samedi 14h-18h30",
    contacts: [{ name: "Jean-François Lebel", phone: "06 87 69 48 64", email: "jflebel@allaire.bzh" }],
    location: "265 rue Saint Hilaire",
  },
  {
    id: "la-fede-centre-social",
    name: "La Fédé - Centre Social Intercommunal",
    description: "Animation enfance/jeunesse, famille/adulte, soutien parentalité",
    icon: "Users2",
    categories: ["Social", "Enfants", "Jeunesse"],
    contacts: [{ name: "Alexia Fournel-Teigné", phone: "02 99 71 99 11", email: "centre.social@lafede.fr" }],
    location: "19 rue de Redon",
  },
  {
    id: "la-fede-epicerie-solidaire",
    name: "La Fédé - Épicerie solidaire 'Graines d'Envies'",
    description: "Épicerie sociale, vestiboutique, ateliers",
    icon: "ShoppingBasket",
    categories: ["Social", "Local"],
    schedule: "Épicerie : Lundi 14h-18h, Mardi 12h-18h\nVestiboutique : Lundi 14h-18h, Mardi 12h-18h, Samedi 10h-12h",
    contacts: [{ name: "Émilie Gorska", phone: "02 99 71 99 11 / 06 95 60 41 84", email: "grainesdenvies@lafede.fr" }],
    location: "1 rue Le Mauff",
  },
  {
    id: "fnaca",
    name: "FNACA",
    description: "Anciens combattants Algérie/Maroc/Tunisie, liens et droits",
    icon: "Shield",
    categories: ["Anciens Combattants"],
    contacts: [
      { name: "Marcel Coyac", role: "Président" },
      { name: "Hélène Chevrel", role: "Secrétaire", phone: "02 99 71 94 16" },
    ],
    fee: "25€/an",
  },
  {
    id: "fnath",
    name: "FNATH",
    description: "Défense droits accidentés/maladies professionnelles",
    icon: "HeartPulse",
    categories: ["Social", "Santé"],
    schedule: "3ème jeudi du mois 11h-12h",
    contacts: [
      { name: "Gilbert Bauthamy", role: "Président" },
      { name: "Patricia Menehy", role: "Secrétaire", phone: "02 99 71 94 48" },
    ],
    location: "Centre associatif",
    fee: "52€/an",
  },
  {
    id: "lhermine-combat-club",
    name: "L'Hermine Combat Club - MMA",
    description: "Arts martiaux mixtes, kickboxing, aérokick",
    icon: "Swords",
    categories: ["Sport", "Arts Martiaux"],
    schedule: "Mercredi 19h30-21h30",
    contacts: [{ name: "Contact", phone: "06 01 76 15 59", email: "lherminecombatclub@gmail.com" }],
    location: "Dojo d'Allaire",
  },
  {
    id: "karate-do-shotokai",
    name: "Karate Do Shotokai Shinbukan",
    description: "Karaté-Do école maître EGAMI, goshin karaté, bô",
    icon: "User",
    categories: ["Sport", "Arts Martiaux"],
    schedule: "Vendredi 17h30-19h30",
    contacts: [
      { name: "Emmanuel Caboulet", role: "Président", phone: "06 46 11 58 45" },
      { name: "Patrick Bonnefoy", phone: "02 97 49 98 81" },
    ],
    location: "Dojo Salle Omnisport",
    fee: "125€ (réduction famille 10€/2ème inscrit)",
  },
  {
    id: "ludotheque",
    name: "Ludothèque",
    description: "Service municipal jeux/jouets, prêt et utilisation sur place",
    icon: "Puzzle",
    categories: ["Loisirs", "Enfants", "Jeunesse"],
    schedule: "Mercredi 14h-17h30, Samedi 14h-17h (hors vacances)",
    contacts: [{ name: "Jean-François Lebel", phone: "06 87 69 48 64", email: "jflebel@allaire.bzh" }],
    location: "265 rue Saint Hilaire",
  },
  {
    id: "mediatheque",
    name: "La Médiathèque",
    description: "Réseau 28 lieux, prêt 4 semaines illimité, ateliers",
    icon: "BookOpen",
    categories: ["Culture", "Loisirs"],
    schedule: "Mardi : 16h30-18h (15h-18h vacances)\nMercredi : 9h30-12h30 et 14h-18h\nVendredi : 15h-19h\nSamedi : 9h30-12h30 et 14h-17h",
    contacts: [{ name: "Contact", phone: "02 99 71 93 58", email: "mediatheque@allaire.bzh" }],
    location: "Modulaire 6 rue Saint Hilaire",
    fee: "Gratuit 1ère année puis 14€ adultes",
  },
  {
    id: "on-ta-vu-sur-la-pointe",
    name: "On t'a vu sur la pointe",
    description: "Théâtre documentaire, spectacles 'Héroïnes', 'Aventurières'",
    icon: "Theater",
    categories: ["Culture", "Théâtre"],
    contacts: [
      { name: "Michel Poirier", role: "Président" },
      { name: "Anne-Cécile Richard", phone: "06 76 93 86 08" },
      { name: "Antoine Malfettes", phone: "06 63 22 18 92" },
      { name: "Contact", email: "ontavusurlapointe@gmail.com" },
    ],
    location: "Centre associatif",
  },
  {
    id: "loree-du-bois",
    name: "L'Orée du Bois - Jardin pédagogique",
    description: "Accueil éducation environnement, potager, activités sensorielles",
    icon: "Sprout",
    categories: ["Environnement", "Nature", "Éducation"],
    contacts: [{ name: "Anne Rondeau", phone: "06 83 86 48 66", email: "oreedubois@mailo.com" }],
    location: "131 Le Val",
  },
  {
    id: "ensemble-paroissial-allaire",
    name: "Ensemble Paroissial d'Allaire",
    description: "Accompagnement parcours vie chrétiens, préparation sacrements",
    icon: "Church",
    categories: ["Culte"],
    schedule: "Permanences mardi-samedi 9h-12h",
    contacts: [{ name: "Contact", phone: "02 99 71 91 05", email: "allaireeglise@gmail.com" }],
    location: "Presbytère, 11 rue Saint Hilaire",
  },
  {
    id: "passpattes",
    name: "Pass'Pattes - Médiation par l'animal",
    description: "Activités thérapeutiques/éducatives assistées par l'animal",
    icon: "Dog",
    categories: ["Santé", "Bien-être", "Animaux"],
    schedule: "Lundi-samedi sur RDV",
    contacts: [
      { name: "Nathalie Pasquet", role: "Présidente", phone: "06 86 73 15 77" },
      { name: "Patrick Le Claire", role: "Secrétaire", email: "passpattes@gmail.com" },
    ],
  },
  {
    id: "peche-detente-couesle",
    name: "Pêche Détente à Coueslé",
    description: "Gestion pêche étangs Coueslé, concours avril",
    icon: "Fish",
    categories: ["Loisirs", "Nature"],
    schedule: "Début février-début novembre",
    contacts: [
      { name: "Serge Colin", role: "Président", phone: "06 71 22 58 86" },
      { name: "Jean-Claude Duchêne", role: "Secrétaire" },
    ],
    location: "Étangs de Coueslé",
    fee: "Journée 7€, Année 50€ adultes/16€ -16ans",
  },
  {
    id: "pil-pol",
    name: "Pil' & Pol' - Pilates & Pole Dance",
    description: "Cours Pilates et Pole Dance en petits groupes (6-7 pers max)",
    icon: "Gem",
    categories: ["Sport", "Danse", "Bien-être"],
    schedule: "Créneaux à définir selon niveaux",
    contacts: [{ name: "Contact", notes: "Cours privé, voir directement avec l'instructeur" }],
    location: "Dojo Salle Omnisports",
  },
  {
    id: "proximservices",
    name: "Proxim'Services",
    description: "Services à domicile (ménage, garde enfants, aide personnes âgées)",
    icon: "ConciergeBell",
    categories: ["Social", "Seniors", "Enfants"],
    schedule: "Lundi-vendredi 9h-12h et RDV après-midi",
    contacts: [
      { name: "Antenne Allaire", phone: "02 99 72 65 32" },
      { name: "Antenne Redon", phone: "02 99 70 38 20" },
    ],
    location: "1 rue Saint Hilaire",
  },
  {
    id: "recyclerie-demain-en-mains",
    name: "Recyclerie Demain En Mains",
    description: "Gestion recyclerie, valorisation déchets, vente/don objets",
    icon: "Recycle",
    categories: ["Environnement", "Social"],
    schedule: "Samedis 10h-18h (accueil dons depuis 21 juin 2025)",
    contacts: [{ name: "Contact", phone: "06 46 03 95 90", email: "recycleriedem@gmail.com" }],
    location: "330 rue de Brancheleux",
  },
  {
    id: "shake-house",
    name: "Shake House",
    description: "Organisation Festival La Rue Râle (hip-hop), soirées concerts",
    icon: "BoomBox",
    categories: ["Culture", "Musique", "Événementiel"],
    contacts: [
      { name: "Louis Renaud & Émeline Nohé", role: "Co-présidents" },
      { name: "Simon Robert & Enora Moal", role: "Co-secrétaires", phone: "07 62 00 88 19" },
      { name: "Contact", email: "contact@laruerale.fr" },
    ],
    website: "laruerale.fr",
  },
  {
    id: "sikour-ty-couesle",
    name: "Sikour Ty Coueslé",
    description: "Aide financière résidents Foyer de Vie, collecte papiers/cartons",
    icon: "HelpingHand",
    categories: ["Social"],
    contacts: [
      { name: "Alain Niol", role: "Président", phone: "06 41 82 04 55" },
      { name: "Yves Cordier", role: "Trésorier", phone: "06 71 34 32 77" },
      { name: "Contact", email: "assosikourtycouesle@gmail.com" },
    ],
    fee: "Cotisation : 15€/an",
  },
  {
    id: "societe-chasse-bude",
    name: "Société de chasse de Bude",
    description: "11 sociétaires, 3 actionnaires, territoire 1000 hectares",
    icon: "Crosshair",
    categories: ["Loisirs", "Nature"],
    schedule: "Samedi/Dimanche 8h30-12h et 14h-19h",
    contacts: [
      { name: "Jean-Louis Barthod", role: "Président", phone: "06 84 07 24 81", email: "jeanlouis.barthod@orange.fr" },
      { name: "Gérard Chevalier", role: "Secrétaire" },
    ],
    fee: "Sociétaire 61€, Actionnaire 350€",
  },
  {
    id: "tas-qua-broyer",
    name: "T'as qu'à broyer !",
    description: "Mutualisation broyeur thermique, réutilisation broyat",
    icon: "Shuffle",
    categories: ["Environnement", "Local"],
    contacts: [
      { name: "Emmanuel Bizeul", role: "Président/Responsable" },
      { name: "Albert Euzenat", role: "Secrétaire", phone: "06 70 31 75 95", email: "albert.euzenat@wanadoo.fr" },
    ],
    fee: "Cotisation : 12€/an",
  },
  {
    id: "team-voisin-co",
    name: "Team Voisin & Co",
    description: "Participation Championnat France Auto-cross",
    icon: "Flag",
    categories: ["Sport"],
    contacts: [{ name: "Cyrille Voisin", phone: "06 98 72 45 91 / 07 70 92 32 63", email: "teamvoisinandco@outlook.fr" }],
    location: "351 La Ville Garel",
  },
  {
    id: "zumba-pilates",
    name: "Zumba fitness & cours de Pilates",
    description: "Zumba, Pilates, Tabata, Gym douce, Mixfit",
    icon: "Zap",
    categories: ["Sport", "Danse", "Bien-être"],
    schedule: "Lundi : Zumba Kids 17h30-18h10, Pilates 18h15-19h10, Tabata 19h15-20h10, Zumba 20h15-21h10\nMercredi : Pilates 17h15-18h10, Gym douce 18h15-19h10, Mixfit 19h15-20h10",
    contacts: [{ name: "Amalia Ollivier", phone: "06 08 09 63 89", email: "philamalia@orange.fr" }],
    location: "Ferme de Coueslé",
    fee: "Zumba Kids 95€, 1-3+ cours/semaine 60-190€",
  }
];

export const allCategories = Array.from(new Set(associations.flatMap(a => a.categories))).sort();
